// ─────────────────────────────────────────────────────────────────────────────
// File: vendors.ts
// Path: lib/mock-data/vendors.ts
// ─────────────────────────────────────────────────────────────────────────────

import type { Vendor } from '@/types'

export const mockVendors: Vendor[] = [
  {
    id: 'vendor-1',
    userId: 'user-4',
    storeName: 'Crafted & Co.',
    storeSlug: 'crafted-and-co',
    tagline: 'Handmade goods with soul',
    description:
      'We are a small team of artisans creating premium handcrafted goods. From leather accessories to woven textiles, every product is made with care and intentionality. We believe in slow fashion and sustainable materials.',
    logo: 'https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=200&q=80',
    banner: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1200&q=80',
    email: 'hello@craftedandco.com',
    phone: '+1 555 100 0001',
    website: 'https://craftedandco.com',
    address: {
      id: 'vaddr-1',
      firstName: 'David',
      lastName: 'Mensah',
      phone: '+1 555 100 0001',
      line1: '22 Artisan Lane',
      city: 'Portland',
      state: 'OR',
      postalCode: '97201',
      country: 'US',
    },
    status: 'active',
    plan: 'growth',
    rating: 4.8,
    reviewCount: 324,
    productCount: 48,
    totalSales: 2140,
    totalRevenue: 87600,
    joinedAt: '2022-11-15T10:00:00Z',
    categories: ['cat-6', 'cat-3'],
    shippingPolicy: 'Ships within 3–5 business days. Free shipping on orders over $75.',
    returnPolicy: '30-day returns on all items in original condition.',
    socialLinks: {
      instagram: 'https://instagram.com/craftedandco',
      twitter: 'https://twitter.com/craftedandco',
    },
  },
  {
    id: 'vendor-2',
    userId: 'user-5',
    storeName: 'Lumière Beauty',
    storeSlug: 'lumiere-beauty',
    tagline: 'Clean beauty, radiant you',
    description:
      'Lumière Beauty is dedicated to clean, cruelty-free skincare and cosmetics. We source the finest natural ingredients from around the world to create products that are gentle on skin and kind to the planet.',
    logo: 'https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=200&q=80',
    banner: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=1200&q=80',
    email: 'hello@lumierebeauty.com',
    phone: '+1 555 100 0002',
    address: {
      id: 'vaddr-2',
      firstName: 'Priya',
      lastName: 'Nair',
      phone: '+1 555 100 0002',
      line1: '5 Blossom Ave',
      city: 'Los Angeles',
      state: 'CA',
      postalCode: '90001',
      country: 'US',
    },
    status: 'active',
    plan: 'starter',
    rating: 4.7,
    reviewCount: 518,
    productCount: 62,
    totalSales: 4820,
    totalRevenue: 136400,
    joinedAt: '2023-01-08T12:00:00Z',
    categories: ['cat-4'],
    shippingPolicy: 'Ships within 1–2 business days. Free shipping on orders over $50.',
    returnPolicy: '14-day returns for unopened products.',
    socialLinks: {
      instagram: 'https://instagram.com/lumierebeauty',
      facebook: 'https://facebook.com/lumierebeauty',
    },
  },
  {
    id: 'vendor-3',
    userId: 'user-6',
    storeName: 'TechNest',
    storeSlug: 'technest',
    tagline: 'Smart tech for smarter lives',
    description:
      'TechNest curates the best in consumer electronics — from smart home devices to audio gear and productivity tools. We test every product before listing to ensure you get only quality that lasts.',
    logo: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=200&q=80',
    banner: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=1200&q=80',
    email: 'support@technest.io',
    phone: '+1 555 100 0003',
    website: 'https://technest.io',
    address: {
      id: 'vaddr-3',
      firstName: 'Lucas',
      lastName: 'Ferreira',
      phone: '+1 555 100 0003',
      line1: '300 Innovation Blvd',
      city: 'Austin',
      state: 'TX',
      postalCode: '73301',
      country: 'US',
    },
    status: 'active',
    plan: 'growth',
    rating: 4.6,
    reviewCount: 892,
    productCount: 134,
    totalSales: 9870,
    totalRevenue: 524000,
    joinedAt: '2023-04-22T08:00:00Z',
    categories: ['cat-1'],
    shippingPolicy: 'Same-day dispatch on orders placed before 2 PM EST.',
    returnPolicy: '30-day hassle-free returns. No questions asked.',
    socialLinks: {
      twitter: 'https://twitter.com/technest',
      instagram: 'https://instagram.com/technest',
    },
  },
  {
    id: 'vendor-4',
    userId: 'user-8',
    storeName: 'Sakura Studio',
    storeSlug: 'sakura-studio',
    tagline: 'Japanese-inspired stationery & art',
    description:
      'Sakura Studio brings the elegance of Japanese paper arts and stationery to the world. Our curated collection features journals, washi tape, ink sets, and illustration prints inspired by Japanese aesthetics.',
    logo: 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=200&q=80',
    banner: 'https://images.unsplash.com/photo-1456735190827-d1262f71b8a3?w=1200&q=80',
    email: 'hello@sakurastudio.co',
    address: {
      id: 'vaddr-4',
      firstName: 'Keiko',
      lastName: 'Tanaka',
      phone: '+1 555 100 0004',
      line1: '18 Cherry Blossom Way',
      city: 'Seattle',
      state: 'WA',
      postalCode: '98101',
      country: 'US',
    },
    status: 'pending',
    plan: 'starter',
    rating: 0,
    reviewCount: 0,
    productCount: 12,
    totalSales: 0,
    totalRevenue: 0,
    joinedAt: '2024-03-01T10:00:00Z',
    categories: ['cat-7', 'cat-6'],
    socialLinks: {
      instagram: 'https://instagram.com/sakurastudio',
    },
  },
  {
    id: 'vendor-5',
    userId: 'user-4',
    storeName: 'Verde Home',
    storeSlug: 'verde-home',
    tagline: 'Sustainable home essentials',
    description:
      'Verde Home offers eco-conscious furniture and home décor crafted from sustainable materials. Each piece is designed to be timeless, functional, and gentle on the environment.',
    logo: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=200&q=80',
    banner: 'https://images.unsplash.com/photo-1484154218962-a197022b5858?w=1200&q=80',
    email: 'info@verdehome.com',
    phone: '+1 555 100 0005',
    address: {
      id: 'vaddr-5',
      firstName: 'David',
      lastName: 'Mensah',
      phone: '+1 555 100 0005',
      line1: '77 Green Street',
      city: 'Denver',
      state: 'CO',
      postalCode: '80201',
      country: 'US',
    },
    status: 'active',
    plan: 'starter',
    rating: 4.5,
    reviewCount: 143,
    productCount: 38,
    totalSales: 870,
    totalRevenue: 52400,
    joinedAt: '2023-07-10T08:00:00Z',
    categories: ['cat-3'],
    shippingPolicy: 'Large items ship via freight within 7–14 days.',
    returnPolicy: '14-day returns. Customer covers return shipping.',
  },
]

export const getVendorBySlug = (slug: string) =>
  mockVendors.find((v) => v.storeSlug === slug)

export const getVendorById = (id: string) =>
  mockVendors.find((v) => v.id === id)

export const getActiveVendors = () =>
  mockVendors.filter((v) => v.status === 'active')

export const getFeaturedVendors = () =>
  mockVendors.filter((v) => v.status === 'active').slice(0, 4)